# Generated by Django 3.0.7 on 2021-03-11 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir de')),
                ('valid_to', models.DateTimeField(verbose_name="Valide jusqu'à")),
                ('discount_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage')),
                ('active', models.BooleanField(verbose_name='actif')),
                ('stock', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coupons restant')),
            ],
            options={
                'ordering': ('-valid_from', '-valid_to'),
            },
        ),
    ]
