# Generated by Django 3.0.7 on 2020-11-19 13:22

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('departement', models.CharField(choices=[('C', 'Commercial'), ('D', 'Direction'), ('M', 'Marketing'), ('SC', 'Service client')], default='D', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('fichier', models.FileField(blank=True, max_length=20, upload_to='fichiers/% d/% m/% Y/')),
                ('message', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formulaire de contact',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('intro', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='slides/', verbose_name='Image')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Article')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=70)),
                ('category', models.CharField(choices=[('IN', 'Intrusion'), ('IC', 'Incendie Conventionnelle'), ('IA', 'Incendie Adressable')], default='IN', max_length=2)),
                ('sous_titre', models.CharField(blank=True, max_length=100, verbose_name='Sous titre')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text en plus')),
                ('info_sup', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='informations suplaimentaires')),
                ('photo', models.ImageField(upload_to='produits/', verbose_name='Photo du produit')),
                ('photo_2', models.ImageField(blank=True, upload_to='produits/', verbose_name='Photo du produit 2')),
                ('fichier_1', models.FileField(blank=True, upload_to='fichiers/', verbose_name='fichier 1')),
                ('fichier_2', models.FileField(blank=True, upload_to='fichiers/', verbose_name='fichier 2')),
                ('fichier_3', models.FileField(blank=True, upload_to='fichiers/', verbose_name='fichier 3')),
                ('fichier_4', models.FileField(blank=True, upload_to='fichiers/', verbose_name='fichier 4')),
            ],
            options={
                'verbose_name': 'Produits',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=70)),
                ('photo', models.ImageField(upload_to='produits/', verbose_name='Photo de la solution')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text en plus')),
                ('photo_2', models.ImageField(blank=True, upload_to='produits/', verbose_name='Photo de la solution')),
            ],
        ),
    ]
