# Generated by Django 3.1.3 on 2020-11-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201119_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='fichier_2',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='fichier_3',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='fichier_4',
        ),
        migrations.AddField(
            model_name='produit',
            name='solution',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='photo',
            field=models.ImageField(upload_to='produits/', verbose_name='Photo de la solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='produits/', verbose_name='Photo 2 de la solution'),
        ),
    ]
