# Generated by Django 3.0.7 on 2021-03-07 10:34

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210307_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Numéro du Produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main.models.product_directory_path, verbose_name='Photo du Produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to=main.models.product_directory_path, verbose_name='Photo du Produit 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='solution',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Solution', verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main.models.solution_directory_path, verbose_name='Photo de la solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to=main.models.solution_directory_path, verbose_name='Photo 2 de la solution'),
        ),
    ]
