# Generated by Django 3.0.7 on 2021-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210307_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('N', 'Nouveau'), ('P', 'Promotion'), ('S', 'Sans Status')], default='S', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Nom du Produit'),
        ),
    ]
