# Generated by Django 3.0.7 on 2021-03-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210317_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Formulaire de Contact'},
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='date_added',
            new_name='date_sent',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='fichier',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Téléphone'),
        ),
    ]
