# Generated by Django 3.0.7 on 2021-03-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210320_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Sujet'),
        ),
    ]
