# Generated by Django 3.0.7 on 2021-03-22 12:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210321_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_1',
            field=models.FileField(blank=True, upload_to=main.models.product_file_directory_path, verbose_name='Fiche Technique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to=main.models.product_directory_path_second_picture, verbose_name='Photo du Produit 2'),
        ),
    ]
