# Generated by Django 3.0.7 on 2021-03-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='Wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Wilaya', verbose_name='Wilaya'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Livraison Active'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Wilaya'),
        ),
    ]
