# Generated by Django 3.0.7 on 2021-03-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210309_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='Wilaya',
            new_name='wilaya',
        ),
    ]
